version: '3.8'

services:
  # postgres db
  db:
    image: postgres
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data_template:/var/lib/postgresql/data
    networks:
      - app-network-template

networks:
  app-network-template:

volumes:
  postgres_data_template:
